# configs/EB-Navigation.yaml
model_name: gpt-4o-mini
model_type: era
down_sample_ratio: 0.03
language_only: 0
eval_sets: ["base"]
chat_history: 0
n_shots: 0
multiview: 0
detection_box: 1
multistep: 0
resolution: 500
exp_name: baseline
visual_icl: 0
tp: 1